### ISSUE TITLE
Export of 16th notes

### ISSUE THREAD

**Issue by MichaelGreen49** [jpvoigt/lilypond-export#32]
I have got the xml export to work on a simple Lilypond file which is all I need it for. However, the exported code exports 16th notes as <type>#{16th}#</type> and this doesn't look correct.

**Comment by jeanas** [comment]
I had opened https://github.com/openlilylib/lilypond-export/pull/31 to fix that last year but I didn't merge it at the time, maybe I just forgot.

Anyway, I've merged it.

**Comment by MichaelGreen49** [comment]
Thank you.
